// Generated by https://quicktype.io

export interface IcostCenterPhenologyList {
    result: boolean;
    msj:    string;
    data:   DataCostCenterPhenology[];
}

export interface DataCostCenterPhenology {
    PHENOLOGYID:  string;
    DESCRIPTION:  string;
    COSTCENTERID: string;
    DURATION:     string;
}
