// Generated by https://quicktype.io

export interface ICostCenterList {
    result: boolean;
    msj:    string;
    data:   DataCostCenter[];
}

export interface DataCostCenter {
    STATUS: string,
    COSTCENTERCODE: string,
    DESCRIPTION: string,
    CULTIVE_VARIETY: string,
    CAMPAIGND_ESCRIPTION: string,
    STAR_TDATE: string,
    AREA_HA: string,
    COSTCENTERID: string,
    VARIETYID: string,
    CAMPAIGNID: string,
    STARTDATE: string,
    FINISHDATE: string,
    AREA: string,
    MESUREID: string,
    CULTIVEID:string
}