// Generated by https://quicktype.io

export interface ICultiveList {
    result: boolean;
    msj:    string;
    data:   DataCultive[];
}

export interface DataCultive {
    CULTIVEID:   string;
    STATUS:      string;
    CULTIVECODE: string;
    DESCRIPTION: string;
    VARIEDADES:  string;
    FENOLOGIAS:  string;
}
