
export interface ICultive {
    result: boolean;
    msj:    string;
    data:   Cultive;
}

export interface Cultive {
    CULTIVEID:   string;
    STATUS:      string;
    CULTIVECODE: string;
    DESCRIPTION: string;
    VARIEDADES:  string;
    FENOLOGIAS:  string;
}


export interface ICultiveNutrientIrrigationList {
    result: boolean;
    msj:    string;
    data:   ICultiveNutrientIrrigation[];
}

export interface ICultiveNutrientIrrigation {
    STATUS:                 string;
    CULTIVEID:              string;
    CULTIVE_DESCRIPTION:    string;
    IRRIGATION_DESCRIPTION: string;
    NUTRIENTES:             string;
}


// Generated by https://quicktype.io

export interface ICultiveNutrientList {
    result: boolean;
    msj:    string;
    data:   DataCultiveNutrient[];
}

export interface DataCultiveNutrient {
    NUTRIENTID:  string;
    DESCRIPTION: string;
    LOWLIMIT:    string;
    HIGHLIMIT:   string;
    STATUS:      string;
    CULTIVEID:   string;
    NUTXCULTID:  string;
}


// Generated by https://quicktype.io

export interface ICultiveNutrientPhenologyList {
    result: boolean;
    msj:    string;
    data:   DataCultiveNutrientPhenology[];
}

export interface DataCultiveNutrientPhenology {
    PHENOLOGYID: string;
    DESCRIPTION: string;
    NUTXCULTID:  string;
    TARGET:      string;
}
