// Generated by https://quicktype.io

export interface IFertilizerList {
    result: boolean;
    msj:    string;
    data:   DataFerilizer[];
}

export interface DataFerilizer {
    FERTILIZERID:      string;
    STATUS:            string;
    FERTILIZERCODE:    string;
    DESCRIPTION:       string;
    MESUREDESCRIPTION: string;
    PRICE:             string;
    ABBREVIATION:      string;
    MESUREID:          string;
    FERTILIZERTYPE:    string;
}
