// Generated by https://quicktype.io

export interface IFuncModule {
    result: boolean;
    msj:    string;
    data:   Datum[];
}

export interface Datum {
    FUNCSID:          string;
    SHORTDESCRIPTION: string;
    LONGDESCRIPTION:  string;
    IMG:              string;
    URL:              string;
    SECUENCE:         string;
}
