// Generated by https://quicktype.io

export interface IMesureTypeList {
    result: boolean;
    msj:    string;
    data:   MesureTypeData[];
}

export interface MesureTypeData {
    MESURETYPEID: string;
    DESCRIPTION:  string;
}
