// Generated by https://quicktype.io

export interface INutrientFertilizerList {
    result: boolean;
    msj:    string;
    data:   DataNutrientFertilizer[];
}

export interface DataNutrientFertilizer {
    NUTRIENTID:    string;
    DESCRIPTION:   string;
    NUTXFERTID:    string;
    CONCENTRATION: string;
    FERTILIZERID:  string;
}
