// Generated by https://quicktype.io

export interface IPhenologyCultiveVarietyList {
    result: boolean;
    msj:    string;
    data:   Data;
}

export interface Data {
    cultivos:            Cultivo[];
    cultivos_variedades: { [key: string]: CultivosVariedades[] };
}

export interface Cultivo {
    CULTIVEID:           string;
    CULTIVE_DESCRIPTION: string;
}

export interface CultivosVariedades {
    VARIETYID:           string;
    VARIETY_DESCRIPTION: string;
}
