// Generated by https://quicktype.io

export interface IPrivilege {
    result: boolean;
    msj:    string;
    data:   Data;
}

export interface Data {
    modulos:           Modulo[];
    arbol:             { [key: string]: Arbol };
    moduloDefault:     string;
    moduloPageDefault: string;
}

export interface Arbol {
    nombre:     string;
    url:        string;
    navegacion: Modulo[];
}

export interface Modulo {
    nombre: string;
    url:    string;
    img:    string;
    id:     string;
}
