// Generated by https://quicktype.io

export interface IRolesList {
    result: boolean;
    msj:    string;
    data:   Datum[];
}

export interface Datum {
    ROLEID:      string;
    DESCRIPTION: string;
}
