// Generated by https://quicktype.io

export interface IUserList {
    result: boolean;
    msj:    string;
    data:   Data;
}

export interface Data {
    columnas: Columnas;
    usuarios: Usuario[];
}

export interface Columnas {
    STATUS:         columna;
    USERCODE:       columna;
    EMAIL:          columna;
    NAME_LASTNAME:  columna;
    NAME:           columna;
    LASTNAME:       columna;
    ROLE:           columna;
    ROLEID:         columna;
    USERID:         columna;
}

export interface columna {
    nombre:  string;
    mostrar: number;
}

export interface Usuario {
    USERID:         string;
    USERCODE:       string;
    EMAIL:          string;
    NAME_LASTNAME:  string;
    NAME:           string;
    LASTNAME:       string;
    ROLEID:         string;
    ROLE:           string;
    STATUS:         string;
}
