// Generated by https://quicktype.io

export interface IUser {
    result: boolean;
    msj:    string;
    data:   Data;
}

export interface Data {
    STATUS:   string;
    NAME:     string;
    LASTNAME: string;
    ROLEID:   string;
    TOKEN:    string;
    USERID:   number;
}
