// Generated by https://quicktype.io
//Modelo para listar
export interface IValveList {
    result: boolean;
    msj:    string;
    data:   DataValve[];
}

export interface DataValve {
    VALVEID:            string;
    VALVECODE:          string;
    DESCRIPTION:        string;
    AREA:               string;
    MESUREID:           string;
    STATUS:             string;
    AREA_MESURE: string;
}

//Modelo para insert y update
export interface IValve {
    result: boolean;
    msj:    string;
    data:   Valve;
}

export interface Valve {
    VALVEID:            string;
    VALVECODE:          string;
    DESCRIPTION:        string;
    AREA:               string;
    MESUREID:           string;
    STATUS:             string;
    AREA_MESURE: string;
}
