// Generated by https://quicktype.io

export interface IVarietyList {
    result: boolean;
    msj:    string;
    data:   DataVariety[];
}

export interface DataVariety {
    VARIETYID:   string;
    VARIETYCODE: string;
    STATUS:      string;
    DESCRIPTION: string;
    CULTIVEID:   string;
}
