// Generated by https://quicktype.io

export interface IVarietyPhenologyList {
    result: boolean;
    msj:    string;
    data:   DataVarietyPhenology[];
}

export interface DataVarietyPhenology {
    PHENOLOGYID:   string;
    DESCRIPTION:   string;
    PHENOXVARIEID: string;
    DURATION:      string;
    VARIETYID:      string;
}
